### ISSUE TITLE
Dependency issues with networkx > 2.3

### ISSUE THREAD

**Issue by james-skelton** [biomedbigdata/BiCoN#9]
Installed BiCoN in a fresh virtual environment, and it appears that BiCoN will not work with `networkx` versions >2.3 (but `setup.py` states >= 2.3 is acceptable).

The exact error with later versions is:

```
~/miniconda3/envs/bicon/lib/python3.7/site-packages/bicon/ants.py in clean_net(self, gene_groups, patients_groups, clusters, L_g, G, GE, d_cut)
    655                 g = nx.subgraph(G, group_g)
    656                 # we are taking only the biggest connected component
--> 657                 comp_big = max(nx.connected_component_subgraphs(g), key=len)
    658                 # measure the degree of each node in it
    659                 dg = dict(nx.degree(comp_big))

AttributeError: module 'networkx' has no attribute 'connected_component_subgraphs'
```

**Comment by Laolga** [comment]
Thank you. This issue was fixed.
